import NavierStokes.ResistiveActualComparison

-- All 46 new theorems and four scalar operator definitions.
#print axioms NavierStokes.ResistiveMagnetic.Slice.time
#print axioms NavierStokes.ResistiveMagnetic.Slice.gradient
#print axioms NavierStokes.ResistiveMagnetic.Slice.laplacian
#print axioms NavierStokes.ResistiveMagnetic.Slice.operator
#print axioms NavierStokes.ResistiveMagnetic.Slice.time_nonneg_at_past_max
#print axioms NavierStokes.ResistiveMagnetic.Slice.second_deriv_nonpos_at_max
#print axioms NavierStokes.ResistiveMagnetic.Slice.second_direction_nonpos
#print axioms NavierStokes.ResistiveMagnetic.Slice.laplacian_nonpos_at_max
#print axioms NavierStokes.ResistiveMagnetic.Slice.nonpos_of_strict
#print axioms NavierStokes.ResistiveMagnetic.Slice.operator_affine
#print axioms NavierStokes.ResistiveMagnetic.Slice.nonpos
#print axioms NavierStokes.ResistiveMagnetic.Slice.comparison
#print axioms NavierStokes.ResistiveMagnetic.Slice.scalarTime_eq
#print axioms NavierStokes.ResistiveMagnetic.Slice.scalarPartial_eq
#print axioms NavierStokes.ResistiveMagnetic.Slice.scalarLaplacian_eq
#print axioms NavierStokes.ResistiveMagnetic.Slice.norm_sq_time
#print axioms NavierStokes.ResistiveMagnetic.Slice.norm_sq_gradient
#print axioms NavierStokes.ResistiveMagnetic.Slice.norm_sq_second
#print axioms NavierStokes.ResistiveMagnetic.Slice.norm_sq_laplacian
#print axioms NavierStokes.ResistiveMagnetic.Slice.squared_equation
#print axioms NavierStokes.ResistiveMagnetic.Slice.squared_inequality
#print axioms NavierStokes.ResistiveMagnetic.Comparison.spatialDerivative_sub_of_differentiable
#print axioms NavierStokes.ResistiveMagnetic.Comparison.spatialLaplacian_sub_of_contDiff_two
#print axioms NavierStokes.ResistiveMagnetic.Comparison.difference_equation_of_slices
#print axioms NavierStokes.ResistiveMagnetic.Comparison.forced_estimate
#print axioms NavierStokes.ResistiveMagnetic.Comparison.ideal_resistive
#print axioms NavierStokes.ResistiveMagnetic.Comparison.resistive_unique
#print axioms NavierStokes.ResistiveMagnetic.Comparison.actual_ideal_resistive
#print axioms NavierStokes.ResistiveMagnetic.Comparison.actual_comparison_constant
#print axioms NavierStokes.ResistiveMagnetic.Comparison.actual_resistive_unique
#print axioms NavierStokes.ResistiveMagnetic.Comparison.periodic_comparison_main
#print axioms NavierStokes.ResistiveMagnetic.Jets.composition
#print axioms NavierStokes.ResistiveMagnetic.Jets.path_jets
#print axioms NavierStokes.ResistiveMagnetic.Jets.closed_time_continuity
#print axioms NavierStokes.ResistiveMagnetic.Jets.laplacian_eq_jet
#print axioms NavierStokes.ResistiveMagnetic.Jets.laplacian_periodic
#print axioms NavierStokes.ResistiveMagnetic.Jets.laplacian_eq_of_slice_eq
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.F_jets
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.F_smooth
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.F_joint
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.inverseF_smooth_at
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.inverseF_jets
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.Y_derivative
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.Y_jets
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.magnetic_jets
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.magnetic_laplacian_continuous
#print axioms NavierStokes.ResistiveMagnetic.Jets.Slab.magnetic_laplacian_continuousOn
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_laplacian_continuousOn
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_laplacian_periodic
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_laplacian_bound

-- Construction and comparison dependencies; each audit is transitive.
#print axioms EulerSmoothBanachFlow.pathFamily_contDiff
#print axioms EulerSmoothBanachFlow.forward_fderiv
#print axioms EulerSmoothBanachFlow.backward_hasFDerivAt_label
#print axioms EulerSmoothBanachFlow.backward_contDiff
#print axioms EulerGevreyComposition.continuous_iteratedFDeriv_of_fderiv_eq_comp
#print axioms NavierStokes.MagneticPeriodicSolution.actualData
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_eq_slab
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_contDiffAt
#print axioms NavierStokes.MagneticPeriodicSolution.Data.magnetic_spatial_smooth
#print axioms NavierStokes.MagneticPeriodicSolution.Data.classicalSolution
#print axioms NavierStokes.MagneticPeriodicMain.periodic_main
#print axioms NavierStokes.ResistiveMagnetic.Comparison.actual_velocity_bounds
#print axioms NavierStokes.ResistiveMagnetic.Comparison.norm_le_of_squared_barrier
