import NavierStokes.MagneticCompactMain

-- Run with: lake env lean scripts/audit_magnetic_compact.lean
-- Audit every public theorem added for compact-seed whole-space transport.
#print axioms NavierStokes.MagneticCompactSeed.support_compact
#print axioms NavierStokes.MagneticCompactSeed.potential_smooth
#print axioms NavierStokes.MagneticCompactSeed.seed_smooth
#print axioms NavierStokes.MagneticCompactSeed.seed_divergence
#print axioms NavierStokes.MagneticCompactSeed.seed_supported
#print axioms NavierStokes.MagneticCompactSeed.seed_compact
#print axioms NavierStokes.MagneticCompactSeed.curl_linear
#print axioms NavierStokes.MagneticCompactSeed.seed_eq_on_plateau
#print axioms NavierStokes.MagneticCompactSeed.seed_local_constant
#print axioms NavierStokes.MagneticCompactSeed.seed_at_center
#print axioms NavierStokes.MagneticCompactFlow.Slab.coefficient_apply
#print axioms NavierStokes.MagneticCompactFlow.Slab.coefficient_lipschitz
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_initial
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_initial
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_Phi
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_Y
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_initial
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_initial
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_continuous
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_continuous
#print axioms NavierStokes.MagneticCompactFlow.Slab.data_velocity
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_hasDerivAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_eq_evolution
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_Phi
#print axioms NavierStokes.MagneticCompactFlow.Slab.extendedF_continuous
#print axioms NavierStokes.MagneticCompactFlow.Slab.extendedF_eq
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_continuousOn
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_continuousOn
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_smooth
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_smooth
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_spatial_smooth
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_det_one
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_divergence_free
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_contDiffAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.extendedF_contDiffAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_contDiffAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_contDiffAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_hasDerivAt
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_induction
#print axioms NavierStokes.MagneticCompactFlow.Slab.Phi_overlap
#print axioms NavierStokes.MagneticCompactFlow.Slab.F_overlap
#print axioms NavierStokes.MagneticCompactFlow.Slab.Y_overlap
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_overlap
#print axioms NavierStokes.MagneticCompactFlow.Slab.transported_support
#print axioms NavierStokes.MagneticCompactFlow.Slab.supportTube_compact
#print axioms NavierStokes.MagneticCompactFlow.Slab.magnetic_supported_tube
#print axioms NavierStokes.MagneticCompactFlow.compact_slab_bounds
#print axioms NavierStokes.MagneticCompactSolution.Data.endpoints_spec
#print axioms NavierStokes.MagneticCompactSolution.Data.exists_endpoint
#print axioms NavierStokes.MagneticCompactSolution.Data.index_spec
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_eq_slab
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_initial
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_eventuallyEq
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_continuousOn
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_contDiffAt
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_spatial_smooth
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_divergence_free
#print axioms NavierStokes.MagneticCompactSolution.Data.magnetic_induction
#print axioms NavierStokes.MagneticCompactSolution.Data.transported_support
#print axioms NavierStokes.MagneticCompactSolution.Data.uniform_support
#print axioms NavierStokes.MagneticCompactSolution.Data.slab_bounds
#print axioms NavierStokes.MagneticCompactMain.velocity_supported
#print axioms NavierStokes.MagneticCompactMain.constructed_conclusions
#print axioms NavierStokes.MagneticCompactMain.whole_space_main
#print axioms NavierStokes.MagneticCompactFlow.Slab.coefficient
#print axioms NavierStokes.MagneticCompactMain.actualData
